# Generated by Django 6.0.2 on 2026-03-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='loanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('address', models.TextField()),
                ('PanNumber', models.CharField(max_length=13)),
                ('employeStatus', models.CharField(max_length=30)),
                ('loan_amount', models.IntegerField()),
                ('loan_duration', models.CharField(max_length=20)),
                ('income', models.IntegerField()),
                ('city', models.TextField()),
                ('status', models.CharField(choices=[('aproved', 'Aproved'), ('reject', 'Reject'), ('pending', 'Pending')], default='panding', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='loanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_amount', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('loan_start_date', models.DateField()),
                ('loan_end_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='paymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loanapplication')),
            ],
        ),
    ]
