# Generated by Django 6.0.2 on 2026-03-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
