# Generated by Django 6.0.2 on 2026-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_loanapplication_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
    ]
