# Generated by Django 6.0.2 on 2026-03-31 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loanapplication_interest_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('home', 'Home Loan')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='interest_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loanmodel'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='profile/default.png', upload_to='profile/')),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
