# Generated by Django 6.0.2 on 2026-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_loanapplication_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_duration',
            field=models.DateField(),
        ),
    ]
