# Generated by Django 6.0.2 on 2026-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_duration',
            field=models.IntegerField(default=12, max_length=12),
        ),
    ]
